num1 = input(int())
num2 = input('Adauga cifra : ')
num3 = input('Adauga cifra : ')
num4 = input('Adauga cifra : ')
num5 = input('Adauga cifra : ')
num6 = input('Adauga cifra : ')
num7 = input('Adauga cifra : ')
num8 = input('Adauga cifra : ')
num9 = input('Adauga cifra : ')
num10 = input('Adauga cifra : ')
print(str(num1+num2+num3+num4+num5+num6+num7+num8+num9+num10)